server:
  port: 1689
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.200.7:3306/lottery_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: idss@1234
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mappers/*.xml
jetcache:
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      uri: redis://192.168.200.8:6379/