#server:
#  port: 1689
#spring:
#  datasource:
##    type: com.alibaba.druid.pool.DruidDataSource
#    driverClassName: com.mysql.jdbc.Driver
##    url: jdbc:mysql://19.168.200.7:3306/lottery_study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#    url: jdbc:mysql://192.168.200.7:3306/lottery_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: idss@1234
server:
  port: 1689
spring:
  datasource:
    url: jdbc:mysql://192.168.200.7:3306/lottery_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: idss@1234
    driverClassName: com.mysql.cj.jdbc.Driver