server:
  port: 1688
spring:
  datasource:
    url: jdbc:mysql://192.168.200.7:3306/argus-citic?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: idss@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: mappers/*.xml